import puppeteer from "puppeteer-core";
const b = await puppeteer.launch({ executablePath: "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser", headless: true, args: ["--no-sandbox"] });
const p = await b.newPage();
let f = 0;
const chk = (l, c) => { if (!c) { console.log("FAIL:", l); f++; } };
await p.goto((process.env.BASE || "http://localhost:4173") + "/", { waitUntil: "networkidle0" });
await p.waitForSelector(".edition-grid", { timeout: 10000 });
await p.keyboard.press("2");
await p.waitForFunction(() => location.pathname === "/classic", { timeout: 5000 });
chk("2 -> classic", true);
await p.keyboard.press("3");
await p.waitForFunction(() => location.pathname === "/paper", { timeout: 5000 });
chk("3 -> paper", true);
await p.keyboard.press("4");
await p.waitForFunction(() => location.pathname === "/aurora", { timeout: 5000 });
chk("4 -> aurora", true);
await p.keyboard.press("5");
await p.waitForFunction(() => location.pathname === "/forge", { timeout: 5000 });
chk("5 -> forge", true);
await p.keyboard.press("1");
await p.waitForFunction(() => location.pathname === "/terminal", { timeout: 5000 });
chk("1 -> terminal", true);
const termPath = new URL(p.url()).pathname;
await p.keyboard.type("1");
await new Promise((r) => setTimeout(r, 400));
chk("typing 1 in terminal input does NOT navigate", await p.evaluate((tp) => location.pathname === tp, termPath));
await p.goto((process.env.BASE || "http://localhost:4173") + "/classic", { waitUntil: "networkidle0" });
await p.keyboard.press("9");
await new Promise((r) => setTimeout(r, 400));
chk("9 does not navigate", await p.evaluate(() => location.pathname === "/classic"));
console.log((process.env.BASE ? "LIVE " : "") + (f === 0 ? "SHORTCUT CHECKS PASS" : f + " FAILURES"));
await b.close();
