import puppeteer from "puppeteer-core";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const b = await puppeteer.launch({ executablePath: "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser", headless: true, args: ["--no-sandbox"] });
const p = await b.newPage();
await p.setViewport({ width: 1440, height: 1000 });
await p.goto("http://localhost:4173/terminal", { waitUntil: "networkidle0" });
await p.waitForSelector(".shell-input", { timeout: 8000 });
await p.waitForFunction(() => !document.querySelector(".boot"), { timeout: 8000 });
await p.click(".shell-input");
await p.keyboard.type("neofetch", { delay: 8 });
await p.keyboard.press("Enter");
await sleep(300);
await p.keyboard.type("cat skills.tree", { delay: 8 });
await p.keyboard.press("Enter");
await sleep(300);
await p.click(".shell-input");
await p.keyboard.type("cowsay hire me", { delay: 8 });
await p.keyboard.press("Enter");
await sleep(400);
await p.screenshot({ path: process.argv[2] || "/tmp/terminal-v3.png" });
await b.close();
